Plaenh 2 drush migrate command
City-of-Helsinki/drupal-helfi-etusivu pull request #110
Opened 2022-09-06 04:07 UTC by TudorCCalin

# [UHF-0000](https://helsinkisolutionoffice.atlassian.net/browse/UHF-0000)

## What was done

* This thing was fixed

## How to install

* Make sure your instance is up and running on correct branch.
  * `git pull origin UHF-0000_insert_correct_branch`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review

* [ ] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* Link to other PR

2022-09-16 16:13 UTC, tapsal requested changes

2022-09-20 07:31 UTC, TudorCCalin commented on conf/cmi/core.extension.yml
> +  migrate_tools: 0
Agree, this is to be used from drush.

2022-09-20 11:23 UTC, TudorCCalin commented on public/modules/custom/helfi_migration/config/install/migrate_plus.migration.newsitem_image_fi.yml
> +# Migration configuration for newsitem content.
done! moved them to migrations

2022-09-20 11:23 UTC, TudorCCalin commented on public/modules/custom/helfi_migration/src/Plugin/migrate/source/NewsitemNode.php
> +use Drupal\migrate\Row;
done

2022-09-20 11:24 UTC, TudorCCalin commented on public/modules/custom/helfi_migration/config/install/migrate_plus.migration_group.newsitem.yml
> +# A "migration group" is - surprise! - a group of migrations. It is used to
some comments were removed

2022-09-20 11:24 UTC, TudorCCalin commented on public/modules/custom/helfi_migration/src/Plugin/migrate/source/NewsitemNode.php
> +          $urlList[] = self::ATOM_NEWS_SOURCE_URL . ((string)$contentId);
fixed

2022-09-20 11:25 UTC, TudorCCalin commented on public/modules/custom/helfi_migration/src/Plugin/migrate/source/NewsitemNode.php
> +      if (count($contentIds) < 100) {
created a PAGE_SIZE constant

2022-09-20 11:25 UTC, TudorCCalin commented on public/modules/custom/helfi_migration/src/Plugin/migrate/source/NewsitemNode.php
> +      $response = $client->request($method, $pageUrl, $options);
done

2022-10-03 05:51 UTC, tapsal approved these changes

2022-10-03 10:14 UTC, merged