UHF-6852: News app accessibility changes
City-of-Helsinki/drupal-helfi-etusivu pull request #165
Opened 2022-10-11 09:52 UTC by jeremysteerio

# [UHF-6852](https://helsinkisolutionoffice.atlassian.net/browse/UHF-6852)

Made changes to news app to resolve accessilibity issues.

## What was done

* Changed / added aria-label translations to for better accessibility compliance

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout origin/UHF-6852-accessibility-changes`
  * `make build`
* Get the HDBT branch as well
  * `composer require drupal/hdbt:dev-UHF-6852-accessibility-changes` 
* Run `make drush-cr`

## How to test
* Navigate to the news archive page https://helfi-etusivu.docker.so/fi/uutiset
* Make some selections from the dropdowns. The filter pills that appear should have aria-label along the lines of "Remove X from search results"
* Inspect the pagination element:
  * Previous -button and Next -button should have aria-labels along the lines of "Move to next page X"
  * Number buttons should have aria-labels along the lines of "Move to page X"

## Designers review

* [x] This PR does not need designers review
* [ ] This PR has been visually reviewed by a designer (Name of the designer)

## Other PRs

* React: https://github.com/City-of-Helsinki/helfi-etusivu-news-search/pull/9
* HDBT:

2022-10-17 07:28 UTC, sakkelaaksonen-siili requested changes
aria-labels appear correctly but always in English only.

2022-10-17 11:09 UTC, sakkelaaksonen-siili approved these changes

2022-10-17 11:47 UTC, sakkelaaksonen-siili approved these changes

2022-10-17 13:53 UTC, jeremysteerio commented
Fix'd missing aria-label for filter pills. Issue was that t function was destructured in the search app which made Drupal translations not work.

2022-10-18 07:39 UTC, lonkaanna approved these changes
Works as intended!

2022-11-21 08:54 UTC, closed without merging