Draft: UHF-8088: Language fallbacks for menu blocks.
City-of-Helsinki/drupal-helfi-etusivu pull request #351
Opened 2023-04-28 07:48 UTC by juho-lehmonen

# [UHF-8088](https://helsinkisolutionoffice.atlassian.net/browse/UHF-8088)

## What was done
New module for recreating certain menu trees based on a fallback languages on alternative languages. Also adds correct lang and dir attributes to specific blocks and regions.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-8088-fallback-languages`
  * `make fresh`
* Install related HDBT branch: `composer require drupal/hdbt:dev-UHF-8088-fallback-languages`
* Edit the following menus and add a placeholder `<nolink>` menu item on the languages you want to test:
  * https://helfi-etusivu.docker.so/fi/admin/structure/menu/manage/header-top-navigation
  * https://helfi-etusivu.docker.so/fi/admin/structure/menu/manage/footer-top-navigation
  * https://helfi-etusivu.docker.so/fi/admin/structure/menu/manage/footer-top-navigation-2
  * https://helfi-etusivu.docker.so/fi/admin/structure/menu/manage/footer-bottom-navigation
* Run `make drush-cr`

## How to test
* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Designers review
* [x] This PR does not need designers review

## Other PRs
* ...

2023-04-28 13:29 UTC, teroelonen commented
Footer bottom menu has `dir` and `lang` attributes but they are no correct when the menu has been translated:

![Screenshot 2023-04-28 at 16 28 27](https://user-images.githubusercontent.com/2276077/235160675-947e2fd4-a88f-42d1-83d4-46f008c654d9.png)
![Screenshot 2023-04-28 at 16 28 35](https://user-images.githubusercontent.com/2276077/235160679-bb2e9a32-858f-48bd-9103-e7c2b30baa53.png)

2023-04-28 13:31 UTC, teroelonen requested changes
Check comments :)

2023-05-08 10:33 UTC, rpnykanen approved these changes

2023-05-11 06:37 UTC, teroelonen commented
> `<nolink>` type links on header top menu look broken on mobile:
> 
> ![Screenshot 2023-04-28 at 16 11 38](https://user-images.githubusercontent.com/2276077/235158653-ace497b8-b611-4d3b-8542-84ba7138966f.png)

Tämä on siirretty erilliseksi tiketiksi: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8419

2023-05-11 09:29 UTC, teroelonen approved these changes
This is good to go on part as well now 🦖

2023-05-11 09:42 UTC, merged