UHF-9829 Main news articles
City-of-Helsinki/drupal-helfi-etusivu pull request #573
Opened 2024-04-09 08:48 UTC by khalima

# [UHF-9829](https://helsinkisolutionoffice.atlassian.net/browse/UHF-9829)

**Notice!** Check and merge the [news article PR](https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/572) before merging this one.

## What was done

- Moved the "ordered news" views admin page styles to etusivu-instance.
- Created the "ordered news articles list" draggable view and added a menu link for it in to the tools menu.
- Created/Updated translations for the news article promoted field, news articles, front page top news paragraph, ordered news list view and ordered news articles list view.
- Added "main news articles" block to "frontpage news" view and added "news article" content type to "of interest" view.

## How to install

* Make sure your helfi-etusivu instance is up and running on latest dev branch.
    * `git pull origin dev`
    * `make fresh`
* Switch to `UHF-9829_main_news_articles` branch in etusivu instance and run `drush deploy`
* Update the HDBT Admin theme
    * `composer require drupal/hdbt_admin:dev-UHF-9829_main_news_articles`
* Run `make drush-cim drush-cr`

## How to test

* [ ] Go to https://helfi-etusivu.docker.so/fi/admin/ordered-news and https://helfi-etusivu.docker.so/fi/admin/ordered-news-articles. Check that the first three or four rows are coloured with green backgrounds
* [ ] Check that code follows our standards

## Continuous documentation

* [ ] This feature has been documented/the documentation has been updated
* [x] This change doesn't require updates to the documentation

## Translations

* [x] Translations have been added to .po -files and included in this PR

## Other PRs

* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/281

2024-04-11 14:53 UTC, teroelonen requested changes
Works well but some issues with the border color on the admin UI still.

2024-04-11 14:53 UTC, teroelonen commented on public/modules/custom/helfi_etusivu/assets/css/views.css
> +      border-bottom: 1px solid rgba(0,0,0,0);
This makes the border transparent. It's not the idea here maybe?

2024-04-11 14:53 UTC, teroelonen commented on public/modules/custom/helfi_etusivu/assets/css/views.css
> +      border-bottom: 1px solid rgba(0,0,0,0);
This makes the border transparent. It's not the idea here maybe?

2024-04-12 04:43 UTC, khalima commented on public/modules/custom/helfi_etusivu/assets/css/views.css
> +      border-bottom: 1px solid rgba(0,0,0,0);
Apparently the original styles were changed along the way. I removed the border styles and added hover styles for the table row.

2024-04-12 07:56 UTC, teroelonen approved these changes
This works well now and looks good 🦖

2024-04-12 09:45 UTC, merged