Uhf 9915
City-of-Helsinki/drupal-helfi-etusivu pull request #622
Opened 2024-05-22 09:20 UTC by j-mys

# [UHF-9915](https://helsinkisolutionoffice.atlassian.net/browse/UHF-9915)

## What was done
Frontpage layout changes

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-9915`
  * `drush cim`
  * `make fresh`
* Run `make drush-cr`

## How to test
Compare frontpage to design

* [ ] Check that this feature works
* [ ] Check that code follows our standards

## Continuous documentation

* [ ] This feature has been documented/the documentation has been updated
* [ ] This change doesn't require updates to the documentation

## Translations

* [ ] Translations have been added to .po -files and included in this PR

## Other PRs

* Link to other PR

2024-05-22 10:37 UTC, teroelonen requested changes

2024-05-22 10:37 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_main-news-articles.scss
> +        @include breakpoint($breakpoint-m) {
Nesting is getting a bit out of hand in this whole file. I think if you refactor the & extender you might not run into this issue so easily too :)

2024-05-22 10:37 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_main-news-articles.scss
> +        padding: 0 28px 0 0;
Let's use variables here as well. The closest would be maybe `$spacing-and-half`

2024-05-22 10:37 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_main-news-articles.scss
> +      width: 100% !important;
!important here too. Remove these.

2024-05-22 10:37 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_index.scss
> +@import 'main-news-articles';
I would name this a bit differently since the paragraph is called top-news so main-news-articles is confusing in this context.

2024-05-22 10:37 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/templates/paragraph/paragraph--front-page-top-news.html.twig
> +  {% embed "@hdbt/misc/component.twig" with
The paragraph should have the option to choose between the two listings and maybe its a bit confusing that the paragraph is called top-news but none of the classes call it that. I would use the class `component--top-news` for the whole wrapper and give it two more variants `component--top-news--news` and `component--top-news--articles` so that it would be clear.

2024-05-23 07:06 UTC, j-mys commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_main-news-articles.scss
> +  &__container {
Makes sense

2024-05-23 07:09 UTC, j-mys commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_main-news-articles.scss
> +    padding-bottom: 64px;
Draft hiccups, cleaned for the finished version

2024-05-23 07:10 UTC, j-mys commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_index.scss
> +@import 'main-news-articles';
Sure, makes sense

2024-05-23 07:10 UTC, j-mys commented on public/themes/custom/hdbt_subtheme/templates/paragraph/paragraph--front-page-top-news.html.twig
> +  {% embed "@hdbt/misc/component.twig" with
Will rework this

2024-05-23 11:14 UTC, teroelonen requested changes
Checked the styles. They are not quite 100% yet and there was some coding standard issues on the styles. Commented on the coding standard issues. After they are fixed the layout improvement can begin.

2024-05-23 11:14 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_top-news.scss
> +  .component__content.top-news {
Maybe target here the `.component__title + .component__content` since that is the one you are overriding.

2024-05-23 11:14 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_top-news.scss
> +    padding-bottom: $spacing;
This is nasty way to write the padding. Either use shorthand `padding: $spacing-double $spacing-double $spacing $spacing-double;` if you want the paddings exactly like this but I think in here you can just remove the padding-bottom since the padding is messed up because of the `news-listing--card-teasers` class that I talk about below.

2024-05-23 11:14 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_top-news.scss
> +  ul {
Let's use classes as selectors, not elements.

2024-05-23 11:14 UTC, teroelonen commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_top-news.scss
> +      margin: 0;
This can be written with the above selector, no need for the li + li

2024-05-24 06:01 UTC, j-mys commented on public/themes/custom/hdbt_subtheme/src/scss/06_components/paragraphs/_top-news.scss
> +  .component__content.top-news {
Makes sense

2024-05-29 12:38 UTC, merged