UHF-10334 article recommendation
City-of-Helsinki/drupal-helfi-etusivu pull request #665
Opened 2024-07-19 06:27 UTC by rpnykanen

# [UHF-10334](https://helsinkisolutionoffice.atlassian.net/browse/UHF-10334)
The implementation missed news article.

## What was done
Added support for news article.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-10334`
  * `make fresh`
* Run `make drush-cr`

## How to test
- run `drush helfi:helfi:annif-entity-defaults`
- run `drush helfi:generate-keywords node news_article`
- run `drush cr`
- Login as admin
- Go edit any article
  - Keywords should have been set
  - show block and show in recommendations checkboxes should be true
- Go view the article
  - You should see recommendations block  

* [ ] Check that this feature works
* [ ] Check that code follows our standards

2024-07-23 05:20 UTC, tuutti requested changes

2024-07-23 05:20 UTC, tuutti commented on public/modules/custom/helfi_etusivu/helfi_etusivu.module
> +  if (isset($bundles['node']['news_article'])) {
This should either be moved to news_article module or the news article module should be merged with this module

2024-07-24 06:19 UTC, tuutti approved these changes

2024-07-24 12:13 UTC, teroelonen approved these changes
This works very well! Nice work 🦖

2024-07-24 12:18 UTC, merged